# Generated by Django 2.1.7 on 2019-03-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.CharField(max_length=10, unique=True)),
                ('usr_pass', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
