# Generated by Django 2.1.7 on 2019-04-15 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='detailsmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licnum', models.CharField(max_length=50)),
                ('carImg', models.ImageField(upload_to='images/')),
                ('speed', models.IntegerField()),
                ('vechilemodel', models.CharField(choices=[('Swift', 'Swift'), ('Ertiga', 'Ertiga'), ('Baleno', 'Baleno'), ('Breeza', 'Breeza'), ('Ciaz', 'Ciaz')], max_length=7)),
                ('user', models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='place', max_length=100)),
                ('city', models.CharField(blank=True, default='place', max_length=10)),
                ('country', models.CharField(blank=True, default='place', max_length=10)),
                ('zipcode', models.CharField(blank=True, default='place', max_length=10)),
                ('user', models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
