# Generated by Django 2.1.7 on 2019-04-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20190415_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsmodel',
            old_name='username',
            new_name='userid',
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='ageofvechile',
            field=models.CharField(default='place', max_length=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license',
            field=models.IntegerField(default=1231),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='vechilemodel',
            field=models.CharField(max_length=7),
        ),
    ]
