# Generated by Django 2.1.7 on 2019-03-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20190311_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_insurance',
        ),
    ]
