# Generated by Django 2.1.7 on 2019-04-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20190415_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsmodel',
            old_name='username',
            new_name='userid',
        ),
    ]
