# Generated by Django 2.0.2 on 2019-03-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0003_delete_user_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailsmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licnum', models.CharField(max_length=50)),
                ('carImg', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
