# Generated by Django 2.1.7 on 2019-04-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20190419_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsmodel',
            name='ageofvechile',
            field=models.CharField(default='place', max_length=10),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='vechilemodel',
            field=models.CharField(max_length=10),
        ),
    ]
