# Generated by Django 2.1.7 on 2019-04-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20190419_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=models.CharField(default='num', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(default='job', max_length=100),
        ),
    ]
