# Generated by Django 2.1.7 on 2019-04-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_auto_20190420_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='number',
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='lplate',
            field=models.CharField(default='lnum', max_length=50),
        ),
    ]
