# Generated by Django 2.0.2 on 2019-03-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_auto_20190329_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsmodel',
            name='speed',
            field=models.CharField(max_length=10),
        ),
    ]
