# Generated by Django 2.0.2 on 2019-03-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_auto_20190329_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsmodel',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
