# Generated by Django 2.0.2 on 2019-03-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_auto_20190329_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsmodel',
            name='vechilemodel',
            field=models.CharField(choices=[('Swift', 'Swift'), ('Ertiga', 'Ertiga'), ('Baleno', 'Baleno'), ('Breeza', 'Breeza'), ('ciaz', 'ciaz')], default=12, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='carImg',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
