# Generated by Django 2.1.7 on 2019-04-25 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginapp', '0010_auto_20190425_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimID', models.CharField(max_length=15)),
                ('claimvalue', models.CharField(max_length=15)),
                ('user_name', models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
