# Generated by Django 2.1.7 on 2019-04-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0012_auto_20190406_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
